### ISSUE TITLE
Included automated download

### ISSUE THREAD

**Issue by prerakmody** [jzagoli/ProstateX2nii#1]
Hi, 
Including my comment as an issue instead of a pull request.

Thanks for this super useful script. I've automated the process a bit more on [this gist](https://gist.github.com/prerakmody/7987e8b62e7c5237747a840b19200692) by including programmatic downloads from the TCIA as well.

Simply run the script, and it shall output a folder `raw/` containing the MRI and masks for each patient.
![image](https://user-images.githubusercontent.com/2803936/194310199-3021f5bb-d0d1-4c74-8119-0d424e06ddd7.png)

**Comment by zagoli** [comment]
Wow, very cool!
And much more cleaner code also 🤩
I'll link your gist in the readme of the repository


Il gio 6 ott 2022, 14:16 pmod ***@***.***> ha scritto:

**Comment by prerakmody** [comment]
Hi,
If you are still using the dataset in your work, I found a small bug in the mri2nii.py code. For e.g. in patients like 129 and 323, the mask overshoots.
You can check the latest update on my gist [here](https://gist.github.com/prerakmody/7987e8b62e7c5237747a840b19200692#file-promise12_prostatex-seg-hires-py-L340)

I've also highlighted the specific section in the snapshot below
![image](https://user-images.githubusercontent.com/2803936/199522840-e6667855-39a8-4903-a475-ba9974b9af48.png)

**Comment by zagoli** [comment]
Great, if you want to open a pull request I'll merge it!
